version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: "true"
  
  redis:
    image: "redis:alpine"


# version: "3.9"

# services:
#   webapp:
#     build: .
#     container_name: webapp
#     ports:
#       - "8000:5000"
  
#   redisdb:
#     image: "redis:alpine"
#     container_name: redis-db