apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f jenkins-chart.yaml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-blueocean
  name: jenkins-blueocean
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: jenkins-blueocean
status:
  loadBalancer: {}
