apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f jenkins-chart.yaml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-blueocean
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - name: "50000"
      port: 50000
      targetPort: 50000
  selector:
    io.kompose.service: jenkins-blueocean
status:
  loadBalancer: {}
