apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f jenkins-chart.yaml convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-blueocean
  name: jenkins-blueocean
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins-blueocean
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f jenkins-chart.yaml convert
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-to-k8s-jenkins: "true"
        io.kompose.service: jenkins-blueocean
    spec:
      containers:
        - env:
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_HOST
              value: tcp://docker:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
          image: jenkins/jenkins:lts
          name: jenkins-blueocean
          ports:
            - containerPort: 8080
              name: http-port
            - containerPort: 50000
              name: jnlp-port
          resources: {}
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-data
            - mountPath: /certs/client
              name: jenkins-docker-certs
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: jenkins-data
          emptyDir: {}
        - name: jenkins-docker-certs
          emptyDir: {}
status: {}
